/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'page-copy': PageCopy;
    programs: Program;
    testimonials: Testimonial;
    faqs: Faq;
    'company-logos': CompanyLogo;
    media: Media;
    lessons: Lesson;
    students: Student;
    enquiries: Enquiry;
    payments: Payment;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'page-copy': PageCopySelect<false> | PageCopySelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'company-logos': CompanyLogosSelect<false> | CompanyLogosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    students: StudentsSelect<false> | StudentsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every word on every page apart from the home page. Open a page, then use the tabs to edit each section. Leave a field blank to keep what's on the site now.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-copy".
 */
export interface PageCopy {
  id: number;
  /**
   * Which page this is.
   */
  title: string;
  /**
   * The web address. Fixed — changing it would break links.
   */
  path: string;
  hero?: {
    /**
     * Small coloured label above the heading.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The supporting paragraph under the heading.
     */
    body?: string | null;
    primaryCtaLabel?: string | null;
    /**
     * Outline button text.
     */
    secondaryCtaLabel?: string | null;
    /**
     * Small line that lowers the risk of clicking. E.g. 'No obligation.'
     */
    reassurance?: string | null;
  };
  pain?: {
    /**
     * Small coloured label above the heading.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The supporting paragraph under the heading.
     */
    body?: string | null;
    /**
     * The specific things they're struggling with.
     */
    items?:
      | {
          /**
           * One emoji.
           */
          icon?: string | null;
          title: string;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * The line that ends the section.
     */
    closing?: string | null;
  };
  importance?: {
    /**
     * Small coloured label above the heading.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The supporting paragraph under the heading.
     */
    body?: string | null;
    /**
     * Reasons this can't wait.
     */
    items?:
      | {
          /**
           * One emoji.
           */
          icon?: string | null;
          title: string;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  benefits?: {
    /**
     * Small coloured label above the heading.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The supporting paragraph under the heading.
     */
    body?: string | null;
    /**
     * What they actually get out of this.
     */
    items?:
      | {
          /**
           * One emoji.
           */
          icon?: string | null;
          title: string;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  consequences?: {
    /**
     * Small coloured label above the heading.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The supporting paragraph under the heading.
     */
    body?: string | null;
    /**
     * One per line.
     */
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  results?: {
    /**
     * Small coloured label above the heading.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The supporting paragraph under the heading.
     */
    body?: string | null;
    /**
     * An unverifiable number is a credibility risk, not a selling point.
     */
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  how?: {
    /**
     * Small coloured label above the heading.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The supporting paragraph under the heading.
     */
    body?: string | null;
    /**
     * Numbered automatically, in order.
     */
    steps?:
      | {
          title: string;
          body?: string | null;
          /**
           * Optional, e.g. 'Week 1' or '45 minutes'.
           */
          duration?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  honesty?: {
    /**
     * Small coloured label above the heading.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    goodFit?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Naming who it's wrong for builds more trust than any guarantee could.
     */
    badFit?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Never promise a job. State plainly what we do and don't control.
     */
    disclaimer?: string | null;
  };
  cta?: {
    /**
     * Small coloured label above the heading.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The supporting paragraph under the heading.
     */
    body?: string | null;
    /**
     * Line that lowers the risk of enquiring.
     */
    reassurance?: string | null;
  };
  seo?: {
    /**
     * Shown in Google results and the browser tab. Under 60 characters.
     */
    title?: string | null;
    /**
     * The grey text under the Google result. Aim for 150–160 characters.
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * The things people can buy. Pricing shown on the site comes from here — change it once and it updates everywhere.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  title: string;
  /**
   * URL-safe id, e.g. career-strategy-gap-analysis
   */
  slug: string;
  /**
   * One line on the pricing card.
   */
  tagline?: string | null;
  /**
   * Who this is genuinely right for. Being honest here reduces refunds and bad reviews.
   */
  bestFor?: string | null;
  /**
   * Shown as-is, e.g. '$349' or 'From $1,200'.
   */
  price?: string | null;
  /**
   * Small print under the price, e.g. 'per person, inc GST'.
   */
  priceNote?: string | null;
  /**
   * E.g. '90 minutes' or '14 days'.
   */
  duration?: string | null;
  /**
   * Asterisked terms and conditions shown under the price. Required by the client.
   */
  terms?: string | null;
  /**
   * Bullet list on the pricing card.
   */
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Describe the change, not the deliverable. 'You stop guessing what recruiters want' beats 'a 10-page report'.
   */
  outcomes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  audience: 'student' | 'employer' | 'education';
  /**
   * The full page for this program, e.g. /students-graduates/career-coaching
   */
  pageUrl?: string | null;
  /**
   * Button text. Keep it casual — the client dislikes 'Enquire Now'.
   */
  ctaLabel?: string | null;
  /**
   * Highlight this card as the most popular option.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real quotes from people Visgrow has worked with. Only publish what you have permission to use.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  /**
   * E.g. 'Engineering graduate, now at Aurecon'.
   */
  role?: string | null;
  /**
   * Their words. Specific beats glowing — 'I stopped getting rejected at screening' lands harder than 'great service'.
   */
  quote: string;
  audience: 'student' | 'employer' | 'education';
  /**
   * Which program this person did. Optional.
   */
  program?: (number | null) | Program;
  /**
   * Optional headshot.
   */
  photo?: (number | null) | Media;
  /**
   * Show this one in the home page carousel.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos, logos and images used anywhere on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines. E.g. 'Mustafa Kadir speaking at a workshop'.
   */
  alt: string;
  /**
   * Optional photographer or source credit.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Answer the awkward questions honestly. Vague answers cost more sales than blunt ones.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * Be direct. Never promise a guaranteed job — say what we actually do and what it depends on.
   */
  answer: string;
  audience: 'student' | 'employer' | 'education' | 'all';
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Show this FAQ on these program pages. Leave blank for site-wide.
   */
  programs?: (number | Program)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Organisations shown in the scrolling logo strip. Only include ones you can evidence — a wrong claim here is a legal problem, not a design one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-logos".
 */
export interface CompanyLogo {
  id: number;
  name: string;
  /**
   * Transparent PNG works best. Uploads are shown on a white tile.
   */
  logo?: (number | null) | Media;
  /**
   * Or use an existing file already in the project, e.g. /images/company-logos/named/pwc.png
   */
  logoPath?: string | null;
  /**
   * Untick to hide without deleting.
   */
  active?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The 14 days of the Accelerator. Students see one new day each day after they start.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  /**
   * 1 to 14. Controls the order and when it unlocks.
   */
  day: number;
  /**
   * E.g. 'Why your resume gets filtered out'.
   */
  title: string;
  /**
   * One or two sentences, shown on the program dashboard before they open it.
   */
  summary?: string | null;
  /**
   * Upload to YouTube as UNLISTED, then paste only the ID — the part after v=. Leave blank and the day shows 'video coming soon'.
   */
  youtubeId?: string | null;
  /**
   * Shown to students so they can plan their time.
   */
  durationMinutes?: number | null;
  /**
   * What they must actually do today. Be specific and finishable in about an hour.
   */
  task?: string | null;
  /**
   * Students tick these off as they go.
   */
  checklist?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  resources?:
    | {
        title: string;
        /**
         * Or upload a file below instead.
         */
        url?: string | null;
        file?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. A personal line at the top of the day — this is what makes it feel coached rather than automated.
   */
  coachNote?: string | null;
  /**
   * Until this is ticked, students never see this day — even if their date has passed.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People enrolled in the 14-Day Accelerator. Add someone here once they've paid and they can sign in straight away.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students".
 */
export interface Student {
  id: number;
  name: string;
  /**
   * This is how they sign in. Must be exact.
   */
  email: string;
  /**
   * Day 1 opens on this date, Day 2 the next day, and so on. Change it to move their whole schedule.
   */
  startDate: string;
  status: 'active' | 'paused' | 'finished' | 'revoked';
  /**
   * Overrides the daily schedule. Useful for someone catching up, or for previewing the program yourself.
   */
  unlockEverything?: boolean | null;
  /**
   * Optional. Links them back to their original enquiry.
   */
  enquiry?: (number | null) | Enquiry;
  /**
   * Updated automatically as they work through the program.
   */
  completedDays?: number[] | null;
  /**
   * Never shown to the student.
   */
  notes?: string | null;
  /**
   * If someone hasn't appeared for a few days, that's your cue to check in.
   */
  lastSeen?: string | null;
  pausedAt?: string | null;
  /**
   * Automatic check-in emails go out at most once a week, and only if they've gone quiet.
   */
  lastNudgedAt?: string | null;
  loginToken?: string | null;
  loginTokenExpires?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everyone who has filled in a form on the website. Newest first. Use the filters to see just the ones you owe a call.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  /**
   * Only for employer and education enquiries.
   */
  organisation?: string | null;
  audience?: ('student' | 'employer' | 'education') | null;
  enquiryType?: string | null;
  /**
   * Set this once you know — it's what makes the pipeline total meaningful.
   */
  program?: (number | null) | Program;
  /**
   * Your estimate. Leave blank if it's too early to say.
   */
  value?: number | null;
  /**
   * In their own words, straight from the form.
   */
  message?: string | null;
  /**
   * Every call, email and meeting. Status changes are added here automatically.
   */
  activity?:
    | {
        date: string;
        type?: ('call' | 'email' | 'meeting' | 'voicemail' | 'status' | 'other') | null;
        note: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Changing this is logged in the contact history.
   */
  status: 'new' | 'contacted' | 'booked' | 'enrolled' | 'closed';
  /**
   * The most useful field here. Filter the list by this to see who you owe a call today.
   */
  followUpDate?: string | null;
  priority?: ('hot' | 'warm' | 'cold') | null;
  /**
   * Which page the form was on.
   */
  source?: string | null;
  /**
   * If this is unticked, do not add them to any marketing list.
   */
  consent?: boolean | null;
  /**
   * Never shown on the website.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every payment taken through the website. Written automatically by Stripe — these can't be edited, so they stay trustworthy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  customerName?: string | null;
  customerEmail?: string | null;
  programName?: string | null;
  /**
   * As charged, including GST.
   */
  amountFormatted?: string | null;
  status?: ('paid' | 'refunded' | 'partially_refunded' | 'failed' | 'disputed') | null;
  paidAt?: string | null;
  program?: (number | null) | Program;
  /**
   * The lead this payment came from, where we could match it.
   */
  enquiry?: (number | null) | Enquiry;
  /**
   * Created automatically for Accelerator purchases.
   */
  student?: (number | null) | Student;
  amountCents?: number | null;
  currency?: string | null;
  /**
   * Search this in your Stripe dashboard to see the full record.
   */
  stripeSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can log in and edit the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in the admin bar.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'page-copy';
        value: number | PageCopy;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'company-logos';
        value: number | CompanyLogo;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'students';
        value: number | Student;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-copy_select".
 */
export interface PageCopySelect<T extends boolean = true> {
  title?: T;
  path?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        primaryCtaLabel?: T;
        secondaryCtaLabel?: T;
        reassurance?: T;
      };
  pain?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              body?: T;
              id?: T;
            };
        closing?: T;
      };
  importance?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  benefits?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              body?: T;
              id?: T;
            };
      };
  consequences?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  results?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  how?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        steps?:
          | T
          | {
              title?: T;
              body?: T;
              duration?: T;
              id?: T;
            };
      };
  honesty?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        goodFit?:
          | T
          | {
              text?: T;
              id?: T;
            };
        badFit?:
          | T
          | {
              text?: T;
              id?: T;
            };
        disclaimer?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        reassurance?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tagline?: T;
  bestFor?: T;
  price?: T;
  priceNote?: T;
  duration?: T;
  terms?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  outcomes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  audience?: T;
  pageUrl?: T;
  ctaLabel?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  quote?: T;
  audience?: T;
  program?: T;
  photo?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  audience?: T;
  order?: T;
  programs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-logos_select".
 */
export interface CompanyLogosSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoPath?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  day?: T;
  title?: T;
  summary?: T;
  youtubeId?: T;
  durationMinutes?: T;
  task?: T;
  checklist?:
    | T
    | {
        text?: T;
        id?: T;
      };
  resources?:
    | T
    | {
        title?: T;
        url?: T;
        file?: T;
        id?: T;
      };
  coachNote?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students_select".
 */
export interface StudentsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  startDate?: T;
  status?: T;
  unlockEverything?: T;
  enquiry?: T;
  completedDays?: T;
  notes?: T;
  lastSeen?: T;
  pausedAt?: T;
  lastNudgedAt?: T;
  loginToken?: T;
  loginTokenExpires?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  organisation?: T;
  audience?: T;
  enquiryType?: T;
  program?: T;
  value?: T;
  message?: T;
  activity?:
    | T
    | {
        date?: T;
        type?: T;
        note?: T;
        id?: T;
      };
  status?: T;
  followUpDate?: T;
  priority?: T;
  source?: T;
  consent?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  customerName?: T;
  customerEmail?: T;
  programName?: T;
  amountFormatted?: T;
  status?: T;
  paidAt?: T;
  program?: T;
  enquiry?: T;
  student?: T;
  amountCents?: T;
  currency?: T;
  stripeSessionId?: T;
  stripePaymentIntentId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Every word on the home page, section by section, in the order they appear. Leave a field blank to keep what's currently on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    /**
     * Small pill above the headline.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * These type themselves out one after another in the headline.
     */
    rotatingWords?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * The supporting paragraph.
     */
    body?: string | null;
    primaryCtaLabel?: string | null;
    /**
     * Outline button text.
     */
    secondaryCtaLabel?: string | null;
    /**
     * Small line under the buttons that lowers the risk of clicking.
     */
    reassurance?: string | null;
  };
  ticker?: {
    /**
     * Line above the scrolling logos. Word this carefully — it must describe something we can evidence.
     */
    caption?: string | null;
  };
  pain?: {
    /**
     * E.g. 'Let's be honest'
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    items?:
      | {
          /**
           * One emoji.
           */
          icon?: string | null;
          title: string;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
    card?: {
      heading?: string | null;
      /**
       * The opening paragraph.
       */
      paragraph?: string | null;
      /**
       * The highlighted box with the orange edge. This is the fact that reframes everything for them.
       */
      callout?: string | null;
      /**
       * The bold line before the button.
       */
      closing?: string | null;
      ctaLabel?: string | null;
    };
  };
  importance?: {
    /**
     * E.g. 'Why this matters now'
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The supporting paragraph.
     */
    body?: string | null;
    /**
     * Four small tiles. Only use figures you can stand behind.
     */
    stats?:
      | {
          /**
           * E.g. 'Most' or 'Seconds'
           */
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  benefits?: {
    /**
     * E.g. 'The Visgrow method'
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The supporting paragraph.
     */
    body?: string | null;
    pillars?:
      | {
          /**
           * E.g. '01 — Coaching'
           */
          number?: string | null;
          title: string;
          body?: string | null;
          ctaLabel?: string | null;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  consequences?: {
    /**
     * E.g. 'What happens if you wait'
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * The quote over the photo.
     */
    imageQuote?: string | null;
    /**
     * The line under the quote.
     */
    imageAttribution?: string | null;
  };
  results?: {
    /**
     * Eyebrow above the numbers.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * These count up as the visitor scrolls. Every one must be defensible — an unverifiable number is a credibility risk, not a selling point.
     */
    stats?:
      | {
          /**
           * Just the number.
           */
          value: number;
          /**
           * E.g. + or %
           */
          suffix?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Eyebrow above the testimonial carousel.
     */
    testimonialsEyebrow?: string | null;
    /**
     * Heading above the testimonial carousel.
     */
    testimonialsHeading?: string | null;
  };
  how?: {
    /**
     * E.g. 'How to get started'
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The supporting paragraph.
     */
    body?: string | null;
    /**
     * Numbered automatically in order.
     */
    steps?:
      | {
          title: string;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  honesty?: {
    /**
     * Eyebrow.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    goodFit?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Naming who it's wrong for builds far more trust than any guarantee could.
     */
    badFit?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Never promise a job here. State plainly what we do and don't control.
     */
    disclaimer?: string | null;
  };
  comparison?: {
    /**
     * Eyebrow.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The supporting paragraph.
     */
    body?: string | null;
  };
  pricing?: {
    /**
     * Eyebrow.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The supporting paragraph.
     */
    body?: string | null;
    /**
     * The asterisked terms under the pricing cards. The individual prices themselves live in Programs.
     */
    footnote?: string | null;
  };
  faq?: {
    /**
     * Eyebrow.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The questions themselves are edited in the FAQs section of the admin.
     */
    note?: string | null;
  };
  enquire?: {
    /**
     * Eyebrow.
     */
    eyebrow?: string | null;
    /**
     * The big headline for this section.
     */
    heading?: string | null;
    /**
     * The supporting paragraph.
     */
    body?: string | null;
    /**
     * Line that lowers the risk of filling the form in.
     */
    reassurance?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Phone number, email, address and the bits that appear on every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  /**
   * Shown at the top of the Terms and Privacy pages, e.g. 'March 2026'. Update it whenever those pages change.
   */
  legalLastUpdated?: string | null;
  /**
   * Registered ABN. Required on the legal pages before launch.
   */
  abn?: string | null;
  /**
   * Registered business name for legal pages.
   */
  businessName?: string | null;
  /**
   * Shown only until you add that day's video. Keep it honest — the student has already paid.
   */
  lessonNoVideoTitle?: string | null;
  lessonNoVideoBody?: string | null;
  /**
   * The YouTube video ID only (the bit after v=). Upload the video as Unlisted. Leave blank to show a 'coming soon' placeholder.
   */
  masterclassYoutubeId?: string | null;
  /**
   * E.g. '48 minutes'. Leave blank until you know — we won't state a length we haven't checked.
   */
  masterclassDuration?: string | null;
  masterclassChapters?:
    | {
        title: string;
        /**
         * Optional, e.g. 04:12
         */
        timestamp?: string | null;
        id?: string | null;
      }[]
    | null;
  audiencePopupEnabled?: boolean | null;
  audiencePopupHeading?: string | null;
  audiencePopupSubheading?: string | null;
  stickyCtaEnabled?: boolean | null;
  stickyCtaText?: string | null;
  social?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The menu across the top of every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Drag to reorder.
   */
  items?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The gradient button on the right.
   */
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The link columns at the bottom of every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * The short paragraph under the logo.
   */
  blurb?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown after the copyright line.
   */
  legalLine?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        rotatingWords?:
          | T
          | {
              text?: T;
              id?: T;
            };
        body?: T;
        primaryCtaLabel?: T;
        secondaryCtaLabel?: T;
        reassurance?: T;
      };
  ticker?:
    | T
    | {
        caption?: T;
      };
  pain?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              body?: T;
              id?: T;
            };
        card?:
          | T
          | {
              heading?: T;
              paragraph?: T;
              callout?: T;
              closing?: T;
              ctaLabel?: T;
            };
      };
  importance?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  benefits?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        pillars?:
          | T
          | {
              number?: T;
              title?: T;
              body?: T;
              ctaLabel?: T;
              href?: T;
              id?: T;
            };
      };
  consequences?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        imageQuote?: T;
        imageAttribution?: T;
      };
  results?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        stats?:
          | T
          | {
              value?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
        testimonialsEyebrow?: T;
        testimonialsHeading?: T;
      };
  how?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        steps?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  honesty?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        goodFit?:
          | T
          | {
              text?: T;
              id?: T;
            };
        badFit?:
          | T
          | {
              text?: T;
              id?: T;
            };
        disclaimer?: T;
      };
  comparison?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
      };
  pricing?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        footnote?: T;
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        note?: T;
      };
  enquire?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        reassurance?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  address?: T;
  legalLastUpdated?: T;
  abn?: T;
  businessName?: T;
  lessonNoVideoTitle?: T;
  lessonNoVideoBody?: T;
  masterclassYoutubeId?: T;
  masterclassDuration?: T;
  masterclassChapters?:
    | T
    | {
        title?: T;
        timestamp?: T;
        id?: T;
      };
  audiencePopupEnabled?: T;
  audiencePopupHeading?: T;
  audiencePopupSubheading?: T;
  stickyCtaEnabled?: T;
  stickyCtaText?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  blurb?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  legalLine?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}